# Additional Env Variables to our App
# You can set Rails/Python/nodeJS env vars as you want
env_variables: {}

# Docker Image Configs
image: {}

# Deployment
deployment: {}

# Pod Disruption Budget
pdb: {}

# Horizontal Pod Autoscaler
hpa: {}

# Service
service: {}

# Ingress
ingress: {}