{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s" .Release.Name | trunc 63 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 | trim }}
  {{- end }}
spec:
  rules:
    - host: {{ .Release.Name }}{{ .Values.ingress.host }}
      http:
        paths:
          - path: {{required "required Ingress Path parameter." .Values.ingress.paths.default.path }}
            pathType: {{required "required Ingress PathType parameter." .Values.ingress.paths.default.pathType }}
            backend:
              service:
                name: {{required "required Ingress Backend ServiceName parameter." .Values.ingress.paths.default.serviceName }}
                port:
                  number: {{required "required Ingress Backend ServicePort parameter." .Values.ingress.paths.default.servicePort }}

{{- end -}}