{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s" .Release.Name | trunc 63 }}
spec:
  minAvailable: {{required "required minAvailable parameter." .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ printf "%s" .Release.Name | trunc 63 }}

{{- end -}}