{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s" .Release.Name | trunc 63 }}
  labels:
    app: {{ printf "%s" .Release.Name | trunc 63 }}
spec:
  type: {{required "required Service Type parameter." .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
  {{ end }}
  selector:
    app: {{ printf "%s" .Release.Name | trunc 63 }}
  ports:
  - name: {{required "required Service Port Name parameter." .Values.service.name }}
    port: {{required "required Service Port parameter." .Values.service.port }}
    protocol: {{required "required Service Port Protocol parameter." .Values.service.protocol }}
    targetPort: {{required "required Service TargetPort parameter." .Values.service.targetPort }}
{{- end -}}