{{- if .Values.service.enabled -}}
{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s" .Release.Name | trunc 63 }}
  labels:
    app: {{ printf "%s" .Release.Name | trunc 63 }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    env: {{ .Values.image.env }}
{{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 | trim }}
{{- end }}
spec:
  ports:
{{ toYaml .Values.service.ports | indent 2 }}
  selector:
    app: {{ printf "%s" .Release.Name | trunc 63 }}
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
  {{ end }}
{{- end -}}